/**
 * sse2neon.h - SSE to NEON translation header
 * 
 * Minimal stub providing core SSE intrinsic compatibility on ARM64.
 * For full compatibility, download from: https://github.com/DLTcollab/sse2neon
 * Auto-generated by Graviton Converter 2.0
 */
#ifndef SSE2NEON_H
#define SSE2NEON_H

#if defined(__aarch64__) || defined(_M_ARM64)
#include <arm_neon.h>
#include <stdlib.h>
#include <string.h>

typedef float32x4_t __m128;
typedef int32x4_t __m128i;
typedef float64x2_t __m128d;

static inline __m128 _mm_setzero_ps(void) { return vdupq_n_f32(0.0f); }
static inline __m128 _mm_set1_ps(float v) { return vdupq_n_f32(v); }
static inline __m128i _mm_setzero_si128(void) { return vdupq_n_s32(0); }
static inline __m128 _mm_loadu_ps(const float *p) { return vld1q_f32(p); }
static inline __m128 _mm_load_ps(const float *p) { return vld1q_f32(p); }
static inline __m128i _mm_loadu_si128(const __m128i *p) { return vld1q_s32((const int32_t *)p); }
static inline void _mm_storeu_ps(float *p, __m128 a) { vst1q_f32(p, a); }
static inline void _mm_store_ps(float *p, __m128 a) { vst1q_f32(p, a); }
static inline void _mm_store_ss(float *p, __m128 a) { *p = vgetq_lane_f32(a, 0); }
static inline void _mm_storeu_si128(__m128i *p, __m128i a) { vst1q_s32((int32_t *)p, a); }
static inline void _mm_stream_si128(__m128i *p, __m128i a) { vst1q_s32((int32_t *)p, a); }
static inline __m128 _mm_add_ps(__m128 a, __m128 b) { return vaddq_f32(a, b); }
static inline __m128 _mm_sub_ps(__m128 a, __m128 b) { return vsubq_f32(a, b); }
static inline __m128 _mm_mul_ps(__m128 a, __m128 b) { return vmulq_f32(a, b); }
static inline __m128 _mm_min_ps(__m128 a, __m128 b) { return vminq_f32(a, b); }
static inline __m128 _mm_max_ps(__m128 a, __m128 b) { return vmaxq_f32(a, b); }
static inline __m128i _mm_xor_si128(__m128i a, __m128i b) { return veorq_s32(a, b); }
static inline void _mm_sfence(void) { __asm__ volatile("dmb ishst" ::: "memory"); }
static inline void _mm_mfence(void) { __asm__ volatile("dmb ish" ::: "memory"); }
static inline void _mm_pause(void) { __asm__ volatile("yield" ::: "memory"); }
#else
#include <immintrin.h>
#endif
#endif /* SSE2NEON_H */
