/**
 * bitops.c - Bit manipulation operations
 * ARM64 version: uses GCC built-ins instead of x86 inline assembly
 * 
 * ⚠️ AUTO-GENERATED by Graviton Converter. Original used x86 POPCNT/BSWAP/BSF/BSR.
 * GCC built-ins compile to optimal ARM64 instructions (CNT, REV, CLZ, RBIT+CLZ).
 * Review before production use.
 */

#include <stdint.h>
#include <stdio.h>

/* Population count - uses GCC built-in (compiles to ARM64 CNT instruction) */
static inline int popcnt32(uint32_t x) {
    return __builtin_popcount(x);
}

static inline int popcnt64(uint64_t x) {
    return __builtin_popcountll(x);
}

/* Byte swap - uses GCC built-in (compiles to ARM64 REV instruction) */
static inline uint32_t bswap32(uint32_t x) {
    return __builtin_bswap32(x);
}

static inline uint64_t bswap64(uint64_t x) {
    return __builtin_bswap64(x);
}

/* Find first set bit from LSB - uses GCC built-in (compiles to ARM64 RBIT+CLZ) */
static inline int find_first_set(uint32_t x) {
    return __builtin_ctz(x);
}

/* Find last set bit from MSB - uses GCC built-in (compiles to ARM64 CLZ) */
static inline int find_last_set(uint32_t x) {
    return 31 - __builtin_clz(x);
}

/* CRC32 - uses ARM64 hardware CRC instruction via built-in */
static inline uint32_t crc32_byte(uint32_t crc, uint8_t data) {
#if defined(__aarch64__) && defined(__ARM_FEATURE_CRC32)
    __asm__("crc32cb %w0, %w0, %w1" : "+r"(crc) : "r"(data));
#else
    crc ^= data;
    for (int i = 0; i < 8; i++) {
        crc = (crc >> 1) ^ (0xEDB88320 & (-(crc & 1)));
    }
#endif
    return crc;
}

/* Count trailing zeros */
int count_trailing_zeros(uint32_t x) {
    if (x == 0) return 32;
    return find_first_set(x);
}

/* Count leading zeros */
int count_leading_zeros(uint32_t x) {
    if (x == 0) return 32;
    return __builtin_clz(x);
}

/* Hamming distance between two integers */
int hamming_distance(uint32_t a, uint32_t b) {
    return popcnt32(a ^ b);
}

/* Reverse byte order in a buffer */
void reverse_bytes(uint32_t *data, int n) {
    for (int i = 0; i < n; i++) {
        data[i] = bswap32(data[i]);
    }
}
