/**
 * timing.c - High-resolution timing
 * ARM64 version: uses CNTVCT_EL0 (virtual counter) instead of RDTSC
 * 
 * ⚠️ AUTO-GENERATED by Graviton Converter. Original used x86 RDTSC/RDTSCP.
 * ARM64 uses the generic timer counter register for cycle-level timing.
 * Review before production use.
 */

#include <stdint.h>
#include <stdio.h>

#if defined(__aarch64__) || defined(_M_ARM64)

/* Read ARM64 virtual counter (equivalent to RDTSC) */
static inline uint64_t rdtsc(void) {
    uint64_t val;
    __asm__ volatile("mrs %0, cntvct_el0" : "=r"(val));
    return val;
}

static inline uint64_t rdtscp(void) {
    uint64_t val;
    __asm__ volatile("isb; mrs %0, cntvct_el0" : "=r"(val));
    return val;
}

static inline void cpu_relax(void) {
    __asm__ volatile("yield" ::: "memory");
}

static inline void memory_barrier(void) {
    __asm__ volatile("dmb ish" ::: "memory");
}

#elif defined(__x86_64__) || defined(_M_X64)

static inline uint64_t rdtsc(void) {
    uint32_t lo, hi;
    __asm__ volatile("rdtsc" : "=a"(lo), "=d"(hi));
    return ((uint64_t)hi << 32) | lo;
}

static inline uint64_t rdtscp(void) {
    uint32_t lo, hi, aux;
    __asm__ volatile("rdtscp" : "=a"(lo), "=d"(hi), "=c"(aux));
    return ((uint64_t)hi << 32) | lo;
}

static inline void cpu_relax(void) {
    __asm__ volatile("pause" ::: "memory");
}

static inline void memory_barrier(void) {
    __asm__ volatile("mfence" ::: "memory");
}

#endif

typedef void (*bench_fn)(void);

double measure_cycles(bench_fn fn, int iterations) {
    uint64_t start, end;
    uint64_t total = 0;

    /* Warmup */
    for (int i = 0; i < 10; i++) {
        fn();
    }

    /* Measure */
    for (int i = 0; i < iterations; i++) {
        memory_barrier();
        start = rdtscp();
        fn();
        end = rdtscp();
        memory_barrier();
        total += (end - start);
    }

    return (double)total / iterations;
}

void print_timing(const char *label, bench_fn fn) {
    double cycles = measure_cycles(fn, 1000);
    printf("%s: %.1f cycles\n", label, cycles);
}
